spring:
  datasource:
    url: jdbc:postgresql://dpg-d25jtsk9c44c73dek3m0-a.oregon-postgres.render.com:5432/bookrentaldb_2mdb
    username: bookrentaldb_2mdb_user
    password: QPQYMQgnX0Mxy7TJtIxqX9TLNssj1Yta
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # <== this is what you need
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: dGhpc2lzYXNhbXBsZXNlY3JldGtleWZvcmp3dGF1dGhlbnRpY2F0aW9u
  expiration: 86400000
